version: '2.1'
services:
  web:
    build: ./build
    restart: always
    ports:
      # limit access for reverse-proxy
      # - "127.0.0.1:7777:7777"
      - "7777:7777"
    environment:
      - POSTGRES_HOST=psql
  psql:
    build: ./psql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
volumes:
  db-data:
networks:
  default:
    ipam:
      config:
        - subnet: 192.100.6.0/24
